Skanus receptai
arminasbrazenas/ReginosReceptai pull request #3
Opened 2022-11-30 20:17 UTC by AugustinasJarockis

Fixed the doubly linked list

2022-11-30 20:26 UTC, arminasbrazenas commented on lib/main.c
> +    insert_tag(name1, "Harambe is good");
k

2022-11-30 20:57 UTC, arminasbrazenas requested changes

2022-11-30 20:57 UTC, arminasbrazenas commented on lib/main.c
> +    insert_text(value);
Maybe insert_tag and insert_text should be one function? Something like `void insert_tag (char *tag, char *params, char *text);`? Then check if text is null. Calling two functions is kind of inconvenient.

2022-11-30 20:57 UTC, arminasbrazenas commented on lib/HTML_code_doubly_linked_list.c
> +        HTML_CODE *field_start = create_HTML_CODE(start_text, _HTML_CURRENT_, (*_HTML_CURRENT_).next);
Unused variables

2022-11-30 20:57 UTC, arminasbrazenas commented on lib/HTML_code_doubly_linked_list.c
> +        HTML_CODE *field_start = create_HTML_CODE(start_text, NULL, NULL);
These three lines in if / else are really similar, could just extract it.

2022-11-30 20:57 UTC, arminasbrazenas commented on lib/HTML_code_doubly_linked_list.c
> +    HTML_CODE *new_elem = malloc(sizeof(HTML_CODE));
There is no point of malloc?

2022-11-30 20:57 UTC, arminasbrazenas commented on lib/HTML_code_doubly_linked_list.c
> +    if(next != NULL)
Format consistently. If you are putting curly brackets on all sentences, put them on all sentences :D Also, after if's and loops there should be a space and before function calls there shouldn't be spaces. It helps to differentiate.

2022-11-30 20:57 UTC, arminasbrazenas commented on lib/HTML_code_doubly_linked_list.c
> +            printf("Failed to open the output file\n");
Could add [strerror ](https://www.tutorialspoint.com/c_standard_library/c_function_strerror.htm)for better experience

2022-11-30 21:01 UTC, AugustinasJarockis commented on lib/HTML_code_doubly_linked_list.c
> +    HTML_CODE *new_elem = malloc(sizeof(HTML_CODE));
There is. Then you leave the function statically allocated variables get destroyed.

2022-11-30 21:04 UTC, AugustinasJarockis commented on lib/main.c
> +    insert_text(value);
Maybe. Depends how text works and if new line matters. But you use it very rarely. I don't know why you believe merging it into one function is more convenient when you need text like 5% of time

2022-11-30 21:04 UTC, AugustinasJarockis commented on lib/HTML_code_doubly_linked_list.c
> +        HTML_CODE *field_start = create_HTML_CODE(start_text, _HTML_CURRENT_, (*_HTML_CURRENT_).next);
Do not really matter. But it is unnecessary.

2022-11-30 21:07 UTC, AugustinasJarockis commented on lib/HTML_code_doubly_linked_list.c
> +            printf("Failed to open the output file\n");
How often do you fail to open a file for writting?

2022-11-30 21:09 UTC, AugustinasJarockis commented on lib/HTML_code_doubly_linked_list.c
> +    if(next != NULL)
Seriously. Tau tarpas nepatinka. Tu checkini ar tai funkcija, ar ifas pagal ifa arba kabliataski gale

2022-11-30 21:14 UTC, AugustinasJarockis commented on lib/HTML_code_doubly_linked_list.c
> +        HTML_CODE *field_start = create_HTML_CODE(start_text, NULL, NULL);
Would make the functions less intuitive to use. Less code is not the only thing you should optimize for.

2022-11-30 21:26 UTC, arminasbrazenas commented on lib/main.c
> +    insert_text(value);
wdym you use it rarely? most of html elements contain text :D

2022-11-30 21:27 UTC, arminasbrazenas commented on lib/HTML_code_doubly_linked_list.c
> +            printf("Failed to open the output file\n");
how often do you fail to allocate memory huh?

2022-11-30 21:27 UTC, arminasbrazenas commented on lib/HTML_code_doubly_linked_list.c
> +        HTML_CODE *field_start = create_HTML_CODE(start_text, _HTML_CURRENT_, (*_HTML_CURRENT_).next);
cleaner code

2022-12-01 17:53 UTC, arminasbrazenas approved these changes

2022-12-01 17:53 UTC, merged